---
version: '2.3'

volumes:
  data-postgres: {}
  data-opennms: {}

networks:
  net-demo:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

services:
  database:
    image: postgres:10
    container_name: demo-database
    env_file:
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    volumes:
      - data-postgres:/var/lib/postgresql/data
    networks:
      net-demo:
        ipv4_address: 172.29.0.5
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 3
    restart: always

  horizon:
    image: no42org/horizon:bleeding
    container_name: demo-horizon
    mem_limit: 3072M
    cap_add:
      - NET_ADMIN
    networks:
      net-demo:
        ipv4_address: 172.29.0.6
    env_file:
      - .opennms.env
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - data-opennms:/opennms-data
      - ./etc-overlay:/opt/opennms-etc-overlay
      - ./logs:/opennms-data/logs
    command: ["-s"]
    ports:
      - "8980:8980"
      - "61616:61616"
    healthcheck:
      test: [ "CMD", "curl", "-f", "-I", "http://localhost:8980/opennms/login.jsp" ]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: always
      
  pris:
    image: opennms/pris:1.1.6
    container_name: demo-pris
    networks:
      net-demo:
        ipv4_address: 172.29.0.7
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./requisitions:/opt/opennms-pris/requisitions
      - ./scriptsteps:/opt/opennms-pris/scriptsteps
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "-I", "http://localhost:8000/documentation/index.html" ]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: always

  dc.srv.01:
    image: opennms/net-snmp:5.7.3-r11-b1
    container_name: dc.srv.01
    networks:
      net-demo:
        ipv4_address: 172.29.0.30
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: [ "CMD", "snmpget", "-v", "2c", "-c", "public", "localhost", ".1.3.6.1.2.1.1.2.0" ]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: always

  dc.srv.02:
    image: opennms/net-snmp:5.7.3-r11-b1
    container_name: dc.srv.02
    networks:
      net-demo:
        ipv4_address: 172.29.0.31
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: [ "CMD", "snmpget", "-v", "2c", "-c", "public", "localhost", ".1.3.6.1.2.1.1.2.0" ]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: always

  dc.srv.03:
    image: opennms/net-snmp:5.7.3-r11-b1
    container_name: dc.srv.03
    networks:
      net-demo:
        ipv4_address: 172.29.0.32
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: [ "CMD", "snmpget", "-v", "2c", "-c", "public", "localhost", ".1.3.6.1.2.1.1.2.0" ]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: always

  dc.srv.04:
    image: opennms/net-snmp:5.7.3-r11-b1
    container_name: dc.srv.04
    networks:
      net-demo:
        ipv4_address: 172.29.0.33
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: [ "CMD", "snmpget", "-v", "2c", "-c", "public", "localhost", ".1.3.6.1.2.1.1.2.0" ]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: always

  dc.srv.05:
    image: opennms/net-snmp:5.7.3-r11-b1
    container_name: dc.srv.05
    networks:
      net-demo:
        ipv4_address: 172.29.0.34
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: [ "CMD", "snmpget", "-v", "2c", "-c", "public", "localhost", ".1.3.6.1.2.1.1.2.0" ]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: always

  dc.srv.06:
    image: opennms/net-snmp:5.7.3-r11-b1
    container_name: dc.srv.06
    networks:
      net-demo:
        ipv4_address: 172.29.0.35
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: [ "CMD", "snmpget", "-v", "2c", "-c", "public", "localhost", ".1.3.6.1.2.1.1.2.0" ]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: always

  dc.srv.07:
    image: opennms/net-snmp:5.7.3-r11-b1
    container_name: dc.srv.07
    networks:
      net-demo:
        ipv4_address: 172.29.0.36
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: [ "CMD", "snmpget", "-v", "2c", "-c", "public", "localhost", ".1.3.6.1.2.1.1.2.0" ]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: always

  dc.srv.08:
    image: opennms/net-snmp:5.7.3-r11-b1
    container_name: dc.srv.08
    networks:
      net-demo:
        ipv4_address: 172.29.0.37
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: [ "CMD", "snmpget", "-v", "2c", "-c", "public", "localhost", ".1.3.6.1.2.1.1.2.0" ]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: always

  dc.srv.09:
    image: opennms/net-snmp:5.7.3-r11-b1
    container_name: dc.srv.09
    networks:
      net-demo:
        ipv4_address: 172.29.0.38
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: [ "CMD", "snmpget", "-v", "2c", "-c", "public", "localhost", ".1.3.6.1.2.1.1.2.0" ]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: always

  dc.srv.10:
    image: opennms/net-snmp:5.7.3-r11-b1
    container_name: dc.srv.10
    networks:
      net-demo:
        ipv4_address: 172.29.0.39
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: [ "CMD", "snmpget", "-v", "2c", "-c", "public", "localhost", ".1.3.6.1.2.1.1.2.0" ]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: always

  dc.srv.11:
    image: opennms/net-snmp:5.7.3-r11-b1
    container_name: dc.srv.11
    networks:
      net-demo:
        ipv4_address: 172.29.0.40
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: [ "CMD", "snmpget", "-v", "2c", "-c", "public", "localhost", ".1.3.6.1.2.1.1.2.0" ]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: always

  dc.srv.12:
    image: opennms/net-snmp:5.7.3-r11-b1
    container_name: dc.srv.12
    networks:
      net-demo:
        ipv4_address: 172.29.0.41
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: [ "CMD", "snmpget", "-v", "2c", "-c", "public", "localhost", ".1.3.6.1.2.1.1.2.0" ]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: always

  dc.web.01:
    image: httpd
    container_name: dc.web.01
    networks:
      net-demo:
        ipv4_address: 172.29.0.50
    environment:
      - TZ=Europe/Berlin
    restart: always

  dc.web.02:
    image: httpd
    container_name: dc.web.02
    networks:
      net-demo:
        ipv4_address: 172.29.0.51
    environment:
      - TZ=Europe/Berlin
    restart: always
  
  dc.web.03:
    image: httpd
    container_name: dc.web.03
    networks:
      net-demo:
        ipv4_address: 172.29.0.52
    environment:
      - TZ=Europe/Berlin
    restart: always
  
  dc.web.04:
    image: httpd
    container_name: dc.web.04
    networks:
      net-demo:
        ipv4_address: 172.29.0.53
    environment:
      - TZ=Europe/Berlin
    restart: always
  
  dc.web.05:
    image: httpd
    container_name: dc.web.05
    networks:
      net-demo:
        ipv4_address: 172.29.0.54
    environment:
      - TZ=Europe/Berlin
    restart: always

  dc.web.06:
    image: httpd
    container_name: dc.web.06
    networks:
      net-demo:
        ipv4_address: 172.29.0.55
    environment:
      - TZ=Europe/Berlin
    restart: always

  dc.web.07:
    image: httpd
    container_name: dc.web.07
    networks:
      net-demo:
        ipv4_address: 172.29.0.56
    environment:
      - TZ=Europe/Berlin
    restart: always
  
  dc.web.08:
    image: httpd
    container_name: dc.web.08
    networks:
      net-demo:
        ipv4_address: 172.29.0.57
    environment:
      - TZ=Europe/Berlin
    restart: always
  
  dc.web.09:
    image: httpd
    container_name: dc.web.09
    networks:
      net-demo:
        ipv4_address: 172.29.0.58
    environment:
      - TZ=Europe/Berlin
    restart: always
