version: 2.0

aliases:
  - &opennms_environment
    - image: opennms/horizon-core-web:23.0.2-1
  - &shellcheck_environment
    - image: opennms/shellcheck:latest

jobs:
  shellcheck:
    docker: *shellcheck_environment
    steps:
      - checkout
      - run:
          name: Shellcheck Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources -e SC2129,SC2001,SC2013
  
  test-opennms-config:
    docker: *opennms_environment
    working_directory: /root/project
    steps:
      - run: 
          name: Add git to retrieve the demo repository
          command: |
            yum -y install git-core
      - checkout
      - run:
          name: Initialise configuration submodules
          command: |
            git submodule update --init
      - run:
          name: Add custom etc overlay configuration
          command: |
            cp -r ./etc-overlay/* /opt/opennms-etc-overlay
      - run:
          name: Test configuration files with OpenNMS config tester
          command: |
            /docker-entrypoint.sh -t -a

workflows:
  version: 2
  container_build_:
    jobs:
      - shellcheck
      - test-opennms-config:
          requires:
            - shellcheck
